name: 'get & cache dependencies'
description: 'Checkout code, cache and install dependencies'
inputs:
  caching:
    description: 'Enable or disable caching of dependencies'
    required: false
    default: 'true'
outputs:
   used-cache: 
     description: 'Cache hit or miss'
     value: ${{ steps.install.outputs.used-cache || steps.cache.outputs.cache-hit }}
runs:
   using: 'composite'
   steps:
      - name: Cache dependencies
        if: inputs.caching == 'true'
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        id: install
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
           npm ci
           echo "used-cache=${{inputs.caching  }}" >> $GITHUB_OUTPUT
        shell: bash